=== gap-system/gap/hpcgap/pkg/gapdoc/gapdoc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ==================================================================
     gapdoc.dtd - XML Document type definition for GAP documentation
     By Frank Lübeck and Max Neunhöffer
     ================================================================== -->


<!-- Note that this definition goes "bottom-up" because entities can only
     be used after their definition in the file. -->


<!-- ==================================================================
     Some entities:
     ================================================================== -->

<!-- The standard XML entities: -->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;">


<!-- The following were introduced in GAPDoc version < 1.0, it is no longer
     necessary to take care of LaTeX special characters
     (we keep the entities with simplified definitions for compatibility) -->
     
<!ENTITY tamp "&amp;">
<!ENTITY tlt "&lt;">
<!ENTITY tgt "&gt;">
<!ENTITY hash "#">
<!ENTITY dollar "$">
<!ENTITY percent "&#37;">
<!ENTITY tilde "~">
<!ENTITY bslash "\\">
<!ENTITY obrace "{">
<!ENTITY cbrace "}">
<!ENTITY uscore "_">
<!ENTITY circum "^">

<!-- ==================================================================
     Our predefined entities:
     ================================================================== -->

<!ENTITY nbsp "&#160;">
<!ENTITY ndash "&#x2013;">
<!ENTITY GAP    "<Package>GAP</Package>">
<!ENTITY GAPDoc "<Package>GAPDoc</Package>">
<!ENTITY TeX    
  "<Alt Only='LaTeX'>{\TeX}</Alt><Alt Not='LaTeX'>TeX</Alt>">
<!ENTITY LaTeX  
  "<Alt Only='LaTeX'>{\LaTeX}</Alt><Alt Not='LaTeX'>LaTeX</Alt>">
<!ENTITY BibTeX 
  "<Alt Only='LaTeX'>{Bib\TeX}</Alt><Alt Not='LaTeX'>BibTeX</Alt>">
<!ENTITY MeatAxe "<Package>MeatAxe</Package>">
<!ENTITY XGAP   "<Package>XGAP</Package>">
<!ENTITY copyright "&#169;">

<!-- and unicode math symbols -->
<!ENTITY CC "&#x2102;" > <!-- double struck -->
<!ENTITY ZZ "&#x2124;" >
<!ENTITY NN "&#x2115;" >
<!ENTITY PP "&#x2119;" >
<!ENTITY QQ "&#x211a;" >
<!ENTITY HH "&#x210d;" >
<!ENTITY RR "&#x211d;" >


<!-- ==================================================================
     The following describes the "innermost" documentation text which 
     can occur at various places in the document like for example
     section headings. It does neither contain further sectioning 
     elements nor environments like Enums or Lists. 
     ================================================================== -->

<!ENTITY % InnerText "#PCDATA |
                      Alt |
                      Emph | E |
                      Par | P | Br |
                      Keyword | K | Arg | A | Quoted | Q | Code | C | 
                      File | F | Button | B | Package |
                      M | Math | Display | 
                      Example | Listing | Log | Verb |
                      URL | Email | Homepage | Address | Cite | Label | 
                      Ref | Index |
                      Ignore" >


<!ELEMENT Alt (%InnerText;)*>     <!-- This is only to allow "Only" and
                                       "Not" attributes for normal text -->
<!ATTLIST Alt Only CDATA #IMPLIED
              Not  CDATA #IMPLIED>

<!-- The following elements declare a certain block of InnerText to
     have a certain property. They are non-terminal and can contain
     any InnerText recursively. -->

<!ELEMENT Emph (%InnerText;)*>    <!-- Emphasize something -->
<!ELEMENT E    (%InnerText;)*>    <!-- the same as shortcut -->


<!-- The following is an empty element marking a paragraph boundary. -->

<!ELEMENT Par EMPTY>    <!-- this is intentionally empty! -->
<!ELEMENT P EMPTY>      <!-- the same as shortcut  -->

<!-- And here is an element for forcing a line break, not starting
     a new paragraph. -->

<!ELEMENT Br EMPTY>     <!-- a forced line break  -->

<!-- The following elements mark a word or sentence to be of a certain
     kind, such that it can  be typeset differently. They are terminal
     elements that should only contain  character data. But we have to
     allow  Alt elements  for handling  special characters.  For these
     elements we introduce  a long name - which is  easy to remember -
     and a  short name - which  you may prefer because  of the shorter
     markup. -->

<!ELEMENT Keyword (#PCDATA|Alt)*>  <!-- Keyword -->
<!ELEMENT K (#PCDATA|Alt)*>        <!-- Keyword (shortcut) -->

<!ELEMENT Arg (#PCDATA|Alt)*>      <!-- Argument -->
<!ELEMENT A (#PCDATA|Alt)*>        <!-- Argument (shortcut) -->

<!ELEMENT Code (#PCDATA|Alt|A|Arg)*> <!-- GAP code -->
<!ELEMENT C (#PCDATA|Alt|A|Arg)*>    <!-- GAP code (shortcut) -->

<!ELEMENT File (#PCDATA|Alt)*>     <!-- Filename -->
<!ELEMENT F (#PCDATA|Alt)*>        <!-- Filename (shortcut) -->

<!ELEMENT Button (#PCDATA|Alt)*>   <!-- "Button" (also Menu, Key) -->
<!ELEMENT B (#PCDATA|Alt)*>        <!-- "Button" (shortcut) -->

<!ELEMENT Package (#PCDATA|Alt)*>  <!-- A package name -->

<!ELEMENT Quoted (%InnerText;)*>   <!-- Quoted (in quotes) text -->
<!ELEMENT Q (%InnerText;)*>        <!-- Quoted text (shortcut) -->


<!-- The following elements contain mathematical formulae. They are 
     terminal elements that contain character data in TeX notation. -->

<!-- Math with well defined translation to text output -->
<!ELEMENT M (#PCDATA|A|Arg|Alt)*>
<!-- Normal TeX math mode formula -->
<!ELEMENT Math (#PCDATA|A|Arg|Alt)*>   
<!-- TeX displayed math mode formula -->
<!ELEMENT Display (#PCDATA|A|Arg|Alt)*>
<!-- Mode="M" causes <M>-style formatting -->
<!ATTLIST Display Mode CDATA #IMPLIED>  


<!-- The  following  elements  contain  GAP related  text  like  code,
     session  logs or  examples. They  are all  terminal elements  and
     consist of character data which is normally typeset verbatim. The
     different  types  of  the  elements only  control  how  they  are
     treated. -->

<!ELEMENT Example (#PCDATA)>  <!-- This is subject to the automatic 
                                   example checking mechanism -->
<!ELEMENT Log (#PCDATA)>      <!-- This not -->
<!ELEMENT Listing (#PCDATA)>  <!-- This is just for code listings -->
<!ATTLIST Listing Type CDATA #IMPLIED> <!-- a comment about the type of
                                            listed code, may appear in
                                            output -->

<!-- One  further  verbatim element,  this is truely  verbatim without
     any processing and intended  for ASCII substitutes of complicated
     displayed formulae or tables. -->

<!ELEMENT Verb  (#PCDATA)> 

<!-- The following  elements are  for cross-referencing  purposes like
     URLs, citations,  references, and  the index. All  these elements
     are  terminal and  need special  methods  to make  up the  actual
     output during document generation. -->

<!ELEMENT URL (#PCDATA|Alt|Link|LinkText)*>  <!-- Link, LinkText
     variant for case where text needs further markup -->
<!ATTLIST URL Text CDATA #IMPLIED>   <!-- This is for output formats
                                          that have links like HTML -->
<!ELEMENT Link     (%InnerText;)*> <!-- the URL -->
<!ELEMENT LinkText (%InnerText;)*> <!-- text for links, can contain markup -->
<!-- The following two are actually URLs, but the element name determines
     the type. -->
<!ELEMENT Email (#PCDATA|Alt|Link|LinkText)*>
<!ELEMENT Homepage (#PCDATA|Alt|Link|LinkText)*>

<!-- Those who still want to give postal addresses can use the following
     element. Use <Br/> for specifying typical line breaks  -->

<!ELEMENT Address (#PCDATA|Alt|Br)*>

<!ELEMENT Cite EMPTY>
<!ATTLIST Cite Key CDATA #REQUIRED
               Where CDATA #IMPLIED>
               
<!ELEMENT Label EMPTY>
<!ATTLIST Label Name CDATA #REQUIRED>

<!ELEMENT Ref EMPTY>
<!ATTLIST Ref Func      CDATA #IMPLIED
              Oper      CDATA #IMPLIED
              Constr    CDATA #IMPLIED
              Meth      CDATA #IMPLIED
              Filt      CDATA #IMPLIED
              Prop      CDATA #IMPLIED
              Attr      CDATA #IMPLIED
              Var       CDATA #IMPLIED
              Fam       CDATA #IMPLIED
              InfoClass CDATA #IMPLIED
              Chap      CDATA #IMPLIED
              Sect      CDATA #IMPLIED
              Subsect   CDATA #IMPLIED
              Appendix  CDATA #IMPLIED
              Text      CDATA #IMPLIED

              Label     CDATA #IMPLIED
              BookName  CDATA #IMPLIED
              Style (Text|Number) #IMPLIED>  <!-- normally automatic -->

<!-- Note that  only one attribute  of Ref is used  normally. BookName
     and  Style  can  be  specified in  addition  to  handle  external
     references and the typesetting style of the reference. -->

<!-- For explicit index entries (Func and so on should cause an
     automatically generated index entry). Use the attributes Key,
     Subkey for sorting (simplified, without markup). The Subkey value
     also gets printed. Use the optional Subkey element if the printed
     version needs some markup.                                        -->
<!ELEMENT Index (%InnerText;|Subkey)*>
<!ATTLIST Index Key    CDATA #IMPLIED
                Subkey CDATA #IMPLIED>
<!ELEMENT Subkey (%InnerText;)*>


<!-- ==================================================================
     The following  describes the normal documentation  text which can
     occur  at various  places in  the document.  It does  not contain
     further sectioning elements. In addition to InnerText it can contain 
     environments like enumerations, lists, and such.
     ================================================================== -->

<!ENTITY % Text "%InnerText; | List | Enum | Table">

<!ELEMENT Item ( %Text;)*>
<!ELEMENT Mark ( %InnerText;)*>

<!ELEMENT List ( ((Mark,Item)|Item)+ )>
<!ATTLIST List Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>
<!ELEMENT Enum ( Item+ )>
<!ATTLIST Enum Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>

<!ELEMENT Table ( Caption?, (Row | HorLine)+ )>
<!ATTLIST Table Label   CDATA #IMPLIED
                Only    CDATA #IMPLIED
                Not     CDATA #IMPLIED
                Align   CDATA #REQUIRED>    <!-- A TeX tabular string -->
                <!-- We allow | and l,c,r, nothing else -->
<!ELEMENT Row   ( Item+ )>
<!ELEMENT HorLine EMPTY>
<!ELEMENT Caption ( %InnerText;)*>

<!-- ==================================================================
     We start defining some things within the overall structure:
     ================================================================== -->

<!-- The TitlePage consists of several sub-elements: -->

<!ELEMENT TitlePage (Title, Subtitle?, Version?, TitleComment?, 
                     Author+, Date?, Address?, Abstract?, Copyright?, 
                     Acknowledgements? , Colophon? )>

<!ELEMENT Title (%Text;)*>
<!ELEMENT Subtitle (%Text;)*>
<!ELEMENT Version (%Text;)*>
<!ELEMENT TitleComment (%Text;)*>
<!ELEMENT Author (%Text;)*>    <!-- There may be more than one Author! -->
<!ELEMENT Date (%Text;)*>
<!ELEMENT Abstract (%Text;)*>
<!ELEMENT Copyright (%Text;)*>
<!ELEMENT Acknowledgements (%Text;)*>  
<!ELEMENT Colophon (%Text;)*>


<!-- The following things just specify some information about the
     corresponding parts of the Book: -->

<!ELEMENT TableOfContents EMPTY>
<!ELEMENT Bibliography EMPTY>
<!ATTLIST Bibliography Databases CDATA #REQUIRED
                       Style CDATA #IMPLIED>
<!ELEMENT TheIndex EMPTY>

<!-- ==================================================================
     The Ignore element can be used everywhere to include further
     information in a GAPDoc document which is not intended for the 
     standard converters (e.g., source code, not yet finished stuff,
     and so on. This information can be extracted by special converter 
     routines, more precise information about the content of an Ignore
     element can be given by the "Remark" attribute.
     ================================================================== -->

<!ELEMENT Ignore (%Text;| Chapter | Section | Subsection | ManSection |
                  Heading)*>
<!ATTLIST Ignore Remark CDATA #IMPLIED>
     
<!-- ==================================================================
     Now we go on with the overall structure by defining the sectioning 
     structure, which includes the Synopsis element: 
     ================================================================== -->


<!ELEMENT Subsection (%Text;| Heading)*>
<!ATTLIST Subsection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT ManSection ( Heading?, 
                      ((Func, Returns?) | (Oper, Returns?) | 
                       (Meth, Returns?) | (Filt, Returns?) | 
                       (Prop, Returns?) | (Attr, Returns?) |
                       (Constr, Returns?) |
                       Var | Fam | InfoClass)+, Description )>
<!ATTLIST ManSection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT Returns (%Text;)*>
<!ELEMENT Description (%Text;)*>


<!-- Note that  the ManSection element  is actually a  subsection with
     respect  to labelling,  referencing, and  counting of  sectioning
     elements. -->

<!ELEMENT Func EMPTY>
<!ATTLIST Func Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!-- Note  that Arg  contains the  full list  of arguments,  including
     optional  parts,  which  are   denoted  by  square  brackets  [].
     Arguments   are  separated   by  whitespace,   commas  count   as
     whitespace. -->

<!-- Note further that although Name and Label are  CDATA (and not ID)
     Label must make up a unique identifier. -->

<!ELEMENT Oper EMPTY>
<!ATTLIST Oper Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Constr EMPTY>
<!ATTLIST Constr Name  CDATA #REQUIRED
                 Label CDATA #IMPLIED
                 Arg   CDATA #REQUIRED
                 Comm  CDATA #IMPLIED>

<!ELEMENT Meth EMPTY>
<!ATTLIST Meth Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Filt EMPTY>
<!ATTLIST Filt Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #IMPLIED
               Comm  CDATA #IMPLIED
               Type  CDATA #IMPLIED>  

<!ELEMENT Prop EMPTY>
<!ATTLIST Prop Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Attr EMPTY>
<!ATTLIST Attr Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Var  EMPTY>
<!ATTLIST Var  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT Fam  EMPTY>
<!ATTLIST Fam  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT InfoClass EMPTY>
<!ATTLIST InfoClass Name  CDATA #REQUIRED
                    Label CDATA #IMPLIED
                    Comm  CDATA #IMPLIED>


<!ELEMENT Heading (%InnerText;)*>

<!ELEMENT Section (%Text;| Heading | Subsection | ManSection)*>
<!ATTLIST Section Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!ELEMENT Chapter (%Text;| Heading | Section)*>
<!ATTLIST Chapter Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!-- Note that  the entity %InnerText; is  documentation that contains
     neither sectioning  elements nor environments  like enumerations,
     but  only  formulae,  labels, references,  citations,  and  other
     terminal elements. -->

<!ELEMENT Appendix (%Text;| Heading | Section)*>
<!ATTLIST Appendix Label CDATA #IMPLIED>   <!-- For reference purposes -->

<!-- Note that  an Appendix  is exactly  the same  as a  Chapter. They
     differ only in the numbering. -->

<!-- ==================================================================
     At last we define the overall structure of a gapdoc Book:
     ================================================================== -->

<!ELEMENT Body  ( %Text;| Chapter | Section )*>

<!ELEMENT Book (TitlePage,
                TableOfContents?,
                Body,
                Appendix*,
                Bibliography?,
                TheIndex?)>
<!ATTLIST Book Name CDATA #REQUIRED>
               
<!-- Note  that  the  entity  %Text; is  documentation  that  contains
     no  further sectioning  elements but  possibly environments  like
     enumerations,  and formulae,  labels, references,  and citations.
     -->

<!-- ============================================================== -->

=== gap-system/gap/hpcgap/doc/hpc/main.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- %W  main.xml        GAP 4 Tutorial        ... -->
<!-- %Y  Copyright 1997, Lehrstuhl D fÃ¼r Mathematik, RWTH Aachen, Germany -->

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
   [ <!ENTITY HPC "<Package>HPC</Package>">
     <!ENTITY mdash "<Alt Only='HTML'>&#8212;</Alt><Alt Not='HTML'>---</Alt>">
<#Include SYSTEM "../versiondata">
   ]>

<?LaTeX ExtraPreamble="
"?>

<Book Name="hpc">
<TitlePage>
  <Title>HPC-GAP &mdash; Reference Manual</Title>
  <Version>Release &VERSIONNUMBER;, &RELEASEDAY;</Version>
  <Author>The GAP Group
    <Email>support@gap-system.org</Email>
    <Homepage>https://www.gap-system.org</Homepage>
  </Author>
  <Author>Reimer Behrends
    <Email>behrends@gmail.com</Email>
  </Author>
  <Author>Vladimir Janjic
    <Email>vj32@st-andrews.ac.uk</Email>
  </Author>
  <Copyright>
    Copyright &copyright; (1987-&RELEASEYEAR;)
    for the core part of the &GAP; system by the &GAP; Group.
    <P/>
    Most parts of this distribution, including the core part of the &GAP;
    system are distributed under the terms of the GNU General Public License,
    see <URL>http://www.gnu.org/licenses/gpl.html</URL> or the file
    <F>GPL</F> in the <F>etc</F> directory of the &GAP;
    installation.
    <P/>
    More detailed information about copyright and licenses of parts of this
    distribution can be found in <Ref Sect="Copyright and License" BookName="ref"/>.
    <P/>
    &GAP; is developed over a long time and has many authors and contributors.
    More detailed information can be found in
    <Ref Sect="Authors and Maintainers" BookName="ref"/>.
  </Copyright>
</TitlePage>

<TableOfContents/>

<Body>
  <#Include SYSTEM "tasks.xml">
  <#Include SYSTEM "vars.xml">
  <#Include SYSTEM "regions.xml">
  <#Include SYSTEM "ui.xml">
  <#Include SYSTEM "aobjects.xml">
  <#Include SYSTEM "threads.xml">
  <#Include SYSTEM "channels.xml">
  <#Include SYSTEM "semaphores.xml">
  <#Include SYSTEM "syncvars.xml">
  <#Include SYSTEM "serialize.xml">
  <#Include SYSTEM "lowlevel.xml">
  <#Include SYSTEM "mpi.xml">
</Body>

<!--
<Bibliography Databases="../manualbib.xml"/>
-->

<!-- <TheIndex/> -->

</Book>

<!-- ==================================================================== -->

=== gap-system/gap/pkg/laguna/doc/manual.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- $Id: manual.xml,v 1.31 2009/05/30 21:13:40 alexk Exp $ -->

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
[<!ENTITY Clanguage "<Package>C</Package>">] 
[<!ENTITY LAG "<Package>LAG</Package>">] 
[<!ENTITY LAGUNA "<Package>LAGUNA</Package>">]
[<!ENTITY SISYPHOS "<Package>SISYPHOS</Package>">] >

<Book Name="LAGUNA">

<TitlePage>
  <Title>&LAGUNA;</Title>
  <Subtitle>Lie AlGebras and UNits of group Algebras</Subtitle>
  <Version>Version 3.5.0</Version>

  <Author>Victor Bovdi 
          <Email>vbovdi@math.klte.hu</Email>
          <Address>
           Institute of Mathematics and Informatics<Br/>
	   University of Debrecen<Br/> 
	   P.O.Box 12, Debrecen, H-4010 Hungary	   </Address>
  </Author>

  <Author>Alexander Konovalov
          <Email>konovalov@member.ams.org</Email>
	  <Homepage>http://www.cs.st-andrews.ac.uk/&tilde;alexk/</Homepage>
          <Address>
            School of Computer Science<Br/>
            University of St Andrews<Br/>
            Jack Cole Building, North Haugh,<Br/>
            St Andrews, Fife, KY16 9SX, Scotland
          </Address> 
  </Author>

  <Author>Richard Rossmanith
          <Email>richard.rossmanith@d-fine.de</Email>
          <Address>
    	    d-fine GmbH<Br/>
            Mergenthalerallee 55
            65760 Eschborn/Frankfurt<Br/>
            Germany
          </Address> 
  </Author>

  <Author>
  Csaba Schneider
  <Email>csaba.schneider@sztaki.hu</Email>
  <Homepage>http://www.sztaki.hu/&tilde;schneider</Homepage>
          <Address>
            Informatics Laboratory<Br/>
            Computer and Automation Research Institute<Br/>
            The Hungarian Academy of Sciences<Br/>
	    1111 Budapest, Lagymanyosi u. 11, Hungary
       </Address> 
  </Author>


  <Date>30 May 2009</Date>

<Abstract>

<Index Key="LAGUNA package">&LAGUNA; package</Index> 
The title ``&LAGUNA;'' stands for ``<B>L</B>ie <B>A</B>l<B>G</B>ebras and 
<B>UN</B>its of group <B>A</B>lgebras''.
This is the new name of the &GAP;4 package &LAG;, which is thus replaced by &LAGUNA;.
<P/>
&LAGUNA; extends the &GAP; functionality for computations in group rings. Besides 
computing some general properties and attributes of group rings and their 
elements, &LAGUNA; is able to perform two main kinds of computations. Namely, 
it can verify  whether a group algebra of a finite group satisfies certain 
Lie properties; and it can calculate the structure of the normalized unit group
of a group algebra of a finite <M>p</M>-group over
the field of <M>p</M> elements.
<P/>

</Abstract>

<Copyright>
  &copyright; 2003-2009 by Victor Bovdi, Alexander Konovalov, 
  Richard Rossmanith, and Csaba Schneider<P/>

  &LAGUNA; is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by 
  the Free Software Foundation; either version 2 of the License, or 
  (at your option) any later version. For details, see the FSF's own site
  <URL>http://www.gnu.org/licenses/gpl.html</URL>.<P/>

  If you obtained &LAGUNA;, we would be grateful for a short notification
  sent to one of the authors.<P/>

  If you publish a result which was partially obtained with the usage of
  &LAGUNA;, please cite it in the following form:<P/>

  V. Bovdi, A. Konovalov, R. Rossmanith and C. Schneider. 
  <E>LAGUNA --- Lie AlGebras and UNits of group Algebras, 
  Version 3.5.0;</E> 2009 
  (<URL>http://www.cs.st-andrews.ac.uk/&tilde;alexk/laguna.htm</URL>).
</Copyright>
  
<Acknowledgements>

Some of the features of &LAGUNA; were already included in the &GAP;4 package
&LAG; written by the third author, Richard Rossmanith. 
<!--which was ported to &GAP;4 during his visit to
St Andrews in September 1998. Since in the new version the functionality
of the package is no longer restricted to Lie algebras, the package
changed its name to &LAGUNA; which means "Lie AlGebras and UNits of group
Algebras".-->
The three other authors first would like to thank Greg Gamble for
maintaining &LAG; and for upgrading it from version 2.0
to version 2.1, and Richard Rossmanith for allowing them to update
and extend the &LAG; package. We are also grateful to Wolfgang Kimmerle
for organizing the workshop ``Computational Group and Group Ring
Theory'' (University of Stuttgart, 28--29 November, 2002), which allowed
us to meet and have fruitful discussions that led towards the final
&LAGUNA; release.
<P/> 
We  are all very grateful to the members of the &GAP; team: Thomas Breuer,
Willem de Graaf, Alexander Hulpke, Stefan Kohl, Steve Linton, Frank L&#252;beck, 
Max Neunh&#246;ffer and many other colleagues for helpful comments and advise.
We acknowledge very much Herbert Pahlings for communicating the package 
and the referee for careful testing &LAGUNA; and useful suggestions.       
<P/> 
A part of the work on upgrading &LAG; to &LAGUNA; was done in 2002 during
Alexander Konovalov's visits to Debrecen, St Andrews and Stuttgart 
Universities.
He would like to express his gratitude to Adalbert Bovdi and
Victor Bovdi, Colin Campbell, Edmund Robertson and Steve Linton,
Wolfgang Kimmerle, Martin Hertweck and Stefan Kohl for their warm
hospitality, and to the NATO Science Fellowship Program, to the London
Mathematical Society and to the DAAD for the support of these visits.     
<P/>

</Acknowledgements>

</TitlePage>

<TableOfContents/>

<Body>

<#Include SYSTEM "intro.xml">
<#Include SYSTEM "example.xml">
<#Include SYSTEM "theory.xml"> 
<#Include SYSTEM "funct.xml">

</Body>

<Bibliography Databases="manual"/>

<TheIndex/>

</Book>

=== gap-system/gap/doc/tut/main.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- %W  main.xml        GAP 4 Tutorial        ... -->
<!-- %Y  Copyright 1997, Lehrstuhl D fÃ¼r Mathematik, RWTH Aachen, Germany -->

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
   [ <!ENTITY ATLAS "<Package>Atlas</Package>">
     <!ENTITY mdash "<Alt Only='HTML'>&#8212;</Alt><Alt Not='HTML'>---</Alt>">
<#Include SYSTEM "../versiondata">
   ]>

<?LaTeX ExtraPreamble="
"?>

<Book Name="tut">
<TitlePage>
  <Title>GAP &mdash; A Tutorial</Title>
  <Version>Release &VERSIONNUMBER;, &RELEASEDAY;</Version>
  <Author>The GAP Group
    <Email>support@gap-system.org</Email>
    <Homepage>https://www.gap-system.org</Homepage>
  </Author>

  <Copyright>
    Copyright &copyright; (1987-&RELEASEYEAR;) 
    for the core part of the &GAP; system by the &GAP; Group.
    <P/>
    Most parts of this distribution, including the core part of the &GAP; 
    system are distributed under the terms of the GNU General Public License, 
    see <URL>https://www.gnu.org/licenses/gpl.html</URL> or the file
    <F>GPL</F> in the <F>etc</F> directory of the &GAP; 
    installation.
    <P/>
    More detailed information about copyright and licenses of parts of this
    distribution can be found in <Ref Sect="Copyright and License" BookName="ref"/>.
    <P/>
    &GAP; is developed over a long time and has many authors and contributors.
    More detailed information can be found in 
    <Ref Sect="Authors and Maintainers" BookName="ref"/>.
  </Copyright>
</TitlePage>

<TableOfContents/>

<Body>

<#Include SYSTEM "preface.xml">
<#Include SYSTEM "introduc.xml">
<#Include SYSTEM "lists.xml">
<#Include SYSTEM "function.xml">
<#Include SYSTEM "group.xml">
<#Include SYSTEM "algvspc.xml">
<#Include SYSTEM "domain.xml">
<#Include SYSTEM "opers.xml">

</Body>

<Bibliography Databases="../manualbib.xml"/>

<TheIndex/>

</Book>

<!-- ==================================================================== -->

=== gap-system/gap/pkg/circle/doc/manual.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- $Id: manual.xml,v 1.8 2008/01/18 15:54:39 alexk Exp $ -->

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
[<!ENTITY Circle "<Package>Circle</Package>">] >

<Book Name="Circle">

<TitlePage>
  <Title>&Circle;</Title>
  <Subtitle>Adjoint groups of finite rings</Subtitle>
  <Version>Version 1.3.1</Version>

  <Author>Alexander Konovalov
          <Email>konovalov@member.ams.org</Email>
	      <Homepage>http://www.cs.st-andrews.ac.uk/&tilde;alexk/</Homepage>
          <Address>
            School of Computer Science<Br/>
            University of St Andrews<Br/>
            Jack Cole Building, North Haugh,<Br/>
            St Andrews, Fife, KY16 9SX, Scotland
          </Address> 
  </Author>

  <Author>Panagiotis Soules
          <Email>psoules@math.uoa.gr</Email>
          <Address>
            Department of Mathematics<Br/>
            National and Capodistrian University of Athens<Br/>
            Panepistimioupolis, GR-15784, Athens, Greece
          </Address>        
  </Author>

  <Date>January 2008</Date>

<Abstract>

<Index Key="Circle package">&Circle; package</Index> 
The &GAP;4 package &Circle; extends the &GAP; functionality 
for computations in adjoint groups of associative rings.
It provides functionality to construct circle objects that will 
respect the circle multiplication <M> r \cdot s = r + s + rs </M>, 
and to compute adjoint semigroups and adjoint groups of finite rings.
<P/>

</Abstract>

<Copyright>

&copyright; 2006-2008 by Alexander Konovalov and Panagiotis Soules
<P/>

&Circle; is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by 
the Free Software Foundation; either version 2 of the License, or 
(at your option) any later version. For details, see the FSF's own site
<URL>http://www.gnu.org/licenses/gpl.html</URL>.
<P/>

If you obtained &Circle;, we would be grateful for a short notification
sent to one of the authors.
<P/>

If you publish a result which was partially obtained with the usage of
&Circle;, please cite it in the following form:
<P/>

A. Konovalov, P. Soules. 
<E>Circle --- Adjoint groups of finite rings, Version 1.3.1;</E> 2008 
(<URL>http://www.cs.st-andrews.ac.uk/&tilde;alexk/circle.htm</URL>).
</Copyright>
  
<Acknowledgements>

We acknowledge very much Alexander Hulpke and James Mitchell 
for their helpful comments and advices, and the referee for 
testing the package and useful suggestions.
<P/> 

</Acknowledgements>

</TitlePage>

<TableOfContents/>

<Body>
<#Include SYSTEM "intro.xml">
<#Include SYSTEM "objects.xml">
<#Include SYSTEM "funct.xml">
<#Include SYSTEM "example.xml">
</Body>

<Bibliography Databases="manual"/>

<TheIndex/>

</Book>
