=== gap-system/gap/hpcgap/pkg/gapdoc/gapdoc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ==================================================================
     gapdoc.dtd - XML Document type definition for GAP documentation
     By Frank Lübeck and Max Neunhöffer
     ================================================================== -->


<!-- Note that this definition goes "bottom-up" because entities can only
     be used after their definition in the file. -->


<!-- ==================================================================
     Some entities:
     ================================================================== -->

<!-- The standard XML entities: -->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;">


<!-- The following were introduced in GAPDoc version < 1.0, it is no longer
     necessary to take care of LaTeX special characters
     (we keep the entities with simplified definitions for compatibility) -->
     
<!ENTITY tamp "&amp;">
<!ENTITY tlt "&lt;">
<!ENTITY tgt "&gt;">
<!ENTITY hash "#">
<!ENTITY dollar "$">
<!ENTITY percent "&#37;">
<!ENTITY tilde "~">
<!ENTITY bslash "\\">
<!ENTITY obrace "{">
<!ENTITY cbrace "}">
<!ENTITY uscore "_">
<!ENTITY circum "^">

<!-- ==================================================================
     Our predefined entities:
     ================================================================== -->

<!ENTITY nbsp "&#160;">
<!ENTITY ndash "&#x2013;">
<!ENTITY GAP    "<Package>GAP</Package>">
<!ENTITY GAPDoc "<Package>GAPDoc</Package>">
<!ENTITY TeX    
  "<Alt Only='LaTeX'>{\TeX}</Alt><Alt Not='LaTeX'>TeX</Alt>">
<!ENTITY LaTeX  
  "<Alt Only='LaTeX'>{\LaTeX}</Alt><Alt Not='LaTeX'>LaTeX</Alt>">
<!ENTITY BibTeX 
  "<Alt Only='LaTeX'>{Bib\TeX}</Alt><Alt Not='LaTeX'>BibTeX</Alt>">
<!ENTITY MeatAxe "<Package>MeatAxe</Package>">
<!ENTITY XGAP   "<Package>XGAP</Package>">
<!ENTITY copyright "&#169;">

<!-- and unicode math symbols -->
<!ENTITY CC "&#x2102;" > <!-- double struck -->
<!ENTITY ZZ "&#x2124;" >
<!ENTITY NN "&#x2115;" >
<!ENTITY PP "&#x2119;" >
<!ENTITY QQ "&#x211a;" >
<!ENTITY HH "&#x210d;" >
<!ENTITY RR "&#x211d;" >


<!-- ==================================================================
     The following describes the "innermost" documentation text which 
     can occur at various places in the document like for example
     section headings. It does neither contain further sectioning 
     elements nor environments like Enums or Lists. 
     ================================================================== -->

<!ENTITY % InnerText "#PCDATA |
                      Alt |
                      Emph | E |
                      Par | P | Br |
                      Keyword | K | Arg | A | Quoted | Q | Code | C | 
                      File | F | Button | B | Package |
                      M | Math | Display | 
                      Example | Listing | Log | Verb |
                      URL | Email | Homepage | Address | Cite | Label | 
                      Ref | Index |
                      Ignore" >


<!ELEMENT Alt (%InnerText;)*>     <!-- This is only to allow "Only" and
                                       "Not" attributes for normal text -->
<!ATTLIST Alt Only CDATA #IMPLIED
              Not  CDATA #IMPLIED>

<!-- The following elements declare a certain block of InnerText to
     have a certain property. They are non-terminal and can contain
     any InnerText recursively. -->

<!ELEMENT Emph (%InnerText;)*>    <!-- Emphasize something -->
<!ELEMENT E    (%InnerText;)*>    <!-- the same as shortcut -->


<!-- The following is an empty element marking a paragraph boundary. -->

<!ELEMENT Par EMPTY>    <!-- this is intentionally empty! -->
<!ELEMENT P EMPTY>      <!-- the same as shortcut  -->

<!-- And here is an element for forcing a line break, not starting
     a new paragraph. -->

<!ELEMENT Br EMPTY>     <!-- a forced line break  -->

<!-- The following elements mark a word or sentence to be of a certain
     kind, such that it can  be typeset differently. They are terminal
     elements that should only contain  character data. But we have to
     allow  Alt elements  for handling  special characters.  For these
     elements we introduce  a long name - which is  easy to remember -
     and a  short name - which  you may prefer because  of the shorter
     markup. -->

<!ELEMENT Keyword (#PCDATA|Alt)*>  <!-- Keyword -->
<!ELEMENT K (#PCDATA|Alt)*>        <!-- Keyword (shortcut) -->

<!ELEMENT Arg (#PCDATA|Alt)*>      <!-- Argument -->
<!ELEMENT A (#PCDATA|Alt)*>        <!-- Argument (shortcut) -->

<!ELEMENT Code (#PCDATA|Alt|A|Arg)*> <!-- GAP code -->
<!ELEMENT C (#PCDATA|Alt|A|Arg)*>    <!-- GAP code (shortcut) -->

<!ELEMENT File (#PCDATA|Alt)*>     <!-- Filename -->
<!ELEMENT F (#PCDATA|Alt)*>        <!-- Filename (shortcut) -->

<!ELEMENT Button (#PCDATA|Alt)*>   <!-- "Button" (also Menu, Key) -->
<!ELEMENT B (#PCDATA|Alt)*>        <!-- "Button" (shortcut) -->

<!ELEMENT Package (#PCDATA|Alt)*>  <!-- A package name -->

<!ELEMENT Quoted (%InnerText;)*>   <!-- Quoted (in quotes) text -->
<!ELEMENT Q (%InnerText;)*>        <!-- Quoted text (shortcut) -->


<!-- The following elements contain mathematical formulae. They are 
     terminal elements that contain character data in TeX notation. -->

<!-- Math with well defined translation to text output -->
<!ELEMENT M (#PCDATA|A|Arg|Alt)*>
<!-- Normal TeX math mode formula -->
<!ELEMENT Math (#PCDATA|A|Arg|Alt)*>   
<!-- TeX displayed math mode formula -->
<!ELEMENT Display (#PCDATA|A|Arg|Alt)*>
<!-- Mode="M" causes <M>-style formatting -->
<!ATTLIST Display Mode CDATA #IMPLIED>  


<!-- The  following  elements  contain  GAP related  text  like  code,
     session  logs or  examples. They  are all  terminal elements  and
     consist of character data which is normally typeset verbatim. The
     different  types  of  the  elements only  control  how  they  are
     treated. -->

<!ELEMENT Example (#PCDATA)>  <!-- This is subject to the automatic 
                                   example checking mechanism -->
<!ELEMENT Log (#PCDATA)>      <!-- This not -->
<!ELEMENT Listing (#PCDATA)>  <!-- This is just for code listings -->
<!ATTLIST Listing Type CDATA #IMPLIED> <!-- a comment about the type of
                                            listed code, may appear in
                                            output -->

<!-- One  further  verbatim element,  this is truely  verbatim without
     any processing and intended  for ASCII substitutes of complicated
     displayed formulae or tables. -->

<!ELEMENT Verb  (#PCDATA)> 

<!-- The following  elements are  for cross-referencing  purposes like
     URLs, citations,  references, and  the index. All  these elements
     are  terminal and  need special  methods  to make  up the  actual
     output during document generation. -->

<!ELEMENT URL (#PCDATA|Alt|Link|LinkText)*>  <!-- Link, LinkText
     variant for case where text needs further markup -->
<!ATTLIST URL Text CDATA #IMPLIED>   <!-- This is for output formats
                                          that have links like HTML -->
<!ELEMENT Link     (%InnerText;)*> <!-- the URL -->
<!ELEMENT LinkText (%InnerText;)*> <!-- text for links, can contain markup -->
<!-- The following two are actually URLs, but the element name determines
     the type. -->
<!ELEMENT Email (#PCDATA|Alt|Link|LinkText)*>
<!ELEMENT Homepage (#PCDATA|Alt|Link|LinkText)*>

<!-- Those who still want to give postal addresses can use the following
     element. Use <Br/> for specifying typical line breaks  -->

<!ELEMENT Address (#PCDATA|Alt|Br)*>

<!ELEMENT Cite EMPTY>
<!ATTLIST Cite Key CDATA #REQUIRED
               Where CDATA #IMPLIED>
               
<!ELEMENT Label EMPTY>
<!ATTLIST Label Name CDATA #REQUIRED>

<!ELEMENT Ref EMPTY>
<!ATTLIST Ref Func      CDATA #IMPLIED
              Oper      CDATA #IMPLIED
              Constr    CDATA #IMPLIED
              Meth      CDATA #IMPLIED
              Filt      CDATA #IMPLIED
              Prop      CDATA #IMPLIED
              Attr      CDATA #IMPLIED
              Var       CDATA #IMPLIED
              Fam       CDATA #IMPLIED
              InfoClass CDATA #IMPLIED
              Chap      CDATA #IMPLIED
              Sect      CDATA #IMPLIED
              Subsect   CDATA #IMPLIED
              Appendix  CDATA #IMPLIED
              Text      CDATA #IMPLIED

              Label     CDATA #IMPLIED
              BookName  CDATA #IMPLIED
              Style (Text|Number) #IMPLIED>  <!-- normally automatic -->

<!-- Note that  only one attribute  of Ref is used  normally. BookName
     and  Style  can  be  specified in  addition  to  handle  external
     references and the typesetting style of the reference. -->

<!-- For explicit index entries (Func and so on should cause an
     automatically generated index entry). Use the attributes Key,
     Subkey for sorting (simplified, without markup). The Subkey value
     also gets printed. Use the optional Subkey element if the printed
     version needs some markup.                                        -->
<!ELEMENT Index (%InnerText;|Subkey)*>
<!ATTLIST Index Key    CDATA #IMPLIED
                Subkey CDATA #IMPLIED>
<!ELEMENT Subkey (%InnerText;)*>


<!-- ==================================================================
     The following  describes the normal documentation  text which can
     occur  at various  places in  the document.  It does  not contain
     further sectioning elements. In addition to InnerText it can contain 
     environments like enumerations, lists, and such.
     ================================================================== -->

<!ENTITY % Text "%InnerText; | List | Enum | Table">

<!ELEMENT Item ( %Text;)*>
<!ELEMENT Mark ( %InnerText;)*>

<!ELEMENT List ( ((Mark,Item)|Item)+ )>
<!ATTLIST List Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>
<!ELEMENT Enum ( Item+ )>
<!ATTLIST Enum Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>

<!ELEMENT Table ( Caption?, (Row | HorLine)+ )>
<!ATTLIST Table Label   CDATA #IMPLIED
                Only    CDATA #IMPLIED
                Not     CDATA #IMPLIED
                Align   CDATA #REQUIRED>    <!-- A TeX tabular string -->
                <!-- We allow | and l,c,r, nothing else -->
<!ELEMENT Row   ( Item+ )>
<!ELEMENT HorLine EMPTY>
<!ELEMENT Caption ( %InnerText;)*>

<!-- ==================================================================
     We start defining some things within the overall structure:
     ================================================================== -->

<!-- The TitlePage consists of several sub-elements: -->

<!ELEMENT TitlePage (Title, Subtitle?, Version?, TitleComment?, 
                     Author+, Date?, Address?, Abstract?, Copyright?, 
                     Acknowledgements? , Colophon? )>

<!ELEMENT Title (%Text;)*>
<!ELEMENT Subtitle (%Text;)*>
<!ELEMENT Version (%Text;)*>
<!ELEMENT TitleComment (%Text;)*>
<!ELEMENT Author (%Text;)*>    <!-- There may be more than one Author! -->
<!ELEMENT Date (%Text;)*>
<!ELEMENT Abstract (%Text;)*>
<!ELEMENT Copyright (%Text;)*>
<!ELEMENT Acknowledgements (%Text;)*>  
<!ELEMENT Colophon (%Text;)*>


<!-- The following things just specify some information about the
     corresponding parts of the Book: -->

<!ELEMENT TableOfContents EMPTY>
<!ELEMENT Bibliography EMPTY>
<!ATTLIST Bibliography Databases CDATA #REQUIRED
                       Style CDATA #IMPLIED>
<!ELEMENT TheIndex EMPTY>

<!-- ==================================================================
     The Ignore element can be used everywhere to include further
     information in a GAPDoc document which is not intended for the 
     standard converters (e.g., source code, not yet finished stuff,
     and so on. This information can be extracted by special converter 
     routines, more precise information about the content of an Ignore
     element can be given by the "Remark" attribute.
     ================================================================== -->

<!ELEMENT Ignore (%Text;| Chapter | Section | Subsection | ManSection |
                  Heading)*>
<!ATTLIST Ignore Remark CDATA #IMPLIED>
     
<!-- ==================================================================
     Now we go on with the overall structure by defining the sectioning 
     structure, which includes the Synopsis element: 
     ================================================================== -->


<!ELEMENT Subsection (%Text;| Heading)*>
<!ATTLIST Subsection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT ManSection ( Heading?, 
                      ((Func, Returns?) | (Oper, Returns?) | 
                       (Meth, Returns?) | (Filt, Returns?) | 
                       (Prop, Returns?) | (Attr, Returns?) |
                       (Constr, Returns?) |
                       Var | Fam | InfoClass)+, Description )>
<!ATTLIST ManSection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT Returns (%Text;)*>
<!ELEMENT Description (%Text;)*>


<!-- Note that  the ManSection element  is actually a  subsection with
     respect  to labelling,  referencing, and  counting of  sectioning
     elements. -->

<!ELEMENT Func EMPTY>
<!ATTLIST Func Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!-- Note  that Arg  contains the  full list  of arguments,  including
     optional  parts,  which  are   denoted  by  square  brackets  [].
     Arguments   are  separated   by  whitespace,   commas  count   as
     whitespace. -->

<!-- Note further that although Name and Label are  CDATA (and not ID)
     Label must make up a unique identifier. -->

<!ELEMENT Oper EMPTY>
<!ATTLIST Oper Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Constr EMPTY>
<!ATTLIST Constr Name  CDATA #REQUIRED
                 Label CDATA #IMPLIED
                 Arg   CDATA #REQUIRED
                 Comm  CDATA #IMPLIED>

<!ELEMENT Meth EMPTY>
<!ATTLIST Meth Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Filt EMPTY>
<!ATTLIST Filt Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #IMPLIED
               Comm  CDATA #IMPLIED
               Type  CDATA #IMPLIED>  

<!ELEMENT Prop EMPTY>
<!ATTLIST Prop Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Attr EMPTY>
<!ATTLIST Attr Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Var  EMPTY>
<!ATTLIST Var  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT Fam  EMPTY>
<!ATTLIST Fam  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT InfoClass EMPTY>
<!ATTLIST InfoClass Name  CDATA #REQUIRED
                    Label CDATA #IMPLIED
                    Comm  CDATA #IMPLIED>


<!ELEMENT Heading (%InnerText;)*>

<!ELEMENT Section (%Text;| Heading | Subsection | ManSection)*>
<!ATTLIST Section Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!ELEMENT Chapter (%Text;| Heading | Section)*>
<!ATTLIST Chapter Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!-- Note that  the entity %InnerText; is  documentation that contains
     neither sectioning  elements nor environments  like enumerations,
     but  only  formulae,  labels, references,  citations,  and  other
     terminal elements. -->

<!ELEMENT Appendix (%Text;| Heading | Section)*>
<!ATTLIST Appendix Label CDATA #IMPLIED>   <!-- For reference purposes -->

<!-- Note that  an Appendix  is exactly  the same  as a  Chapter. They
     differ only in the numbering. -->

<!-- ==================================================================
     At last we define the overall structure of a gapdoc Book:
     ================================================================== -->

<!ELEMENT Body  ( %Text;| Chapter | Section )*>

<!ELEMENT Book (TitlePage,
                TableOfContents?,
                Body,
                Appendix*,
                Bibliography?,
                TheIndex?)>
<!ATTLIST Book Name CDATA #REQUIRED>
               
<!-- Note  that  the  entity  %Text; is  documentation  that  contains
     no  further sectioning  elements but  possibly environments  like
     enumerations,  and formulae,  labels, references,  and citations.
     -->

<!-- ============================================================== -->

=== gap-system/gap/pkg/openmath/doc/manual.xml
<!-- $Id: manual.xml,v 1.11 2010/03/30 11:32:30 alexk Exp $ -->

<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
[<!ENTITY IO "<Package>IO</Package>">]
[<!ENTITY OpenMath "<Package>OpenMath</Package>">]
[<!ENTITY scscp1 "<Package>scscp1</Package>">]
[<!ENTITY scscp2 "<Package>scscp2</Package>">]
[<!ENTITY SCSCP "<Package>SCSCP</Package>">] >

<Book Name="openmath">

<TitlePage>
  <Title>&OpenMath;</Title>
  <Subtitle>&OpenMath; functionality in GAP</Subtitle>
  <Version>Version 10.1.0</Version>

  <Author>Marco Costantini
          <Email>costanti at science dot unitn dot it</Email>
	      <!-- <Homepage>http://www-math.science.unitn.it/&tilde;costanti/</Homepage> -->
	      <Address>
            Department of Mathematics<Br/>
            University of Trento<Br/>
          </Address> 
  </Author> 
    
  <Author>Alexander Konovalov
          <Email>alexk at mcs dot st-andrews dot ac dot uk</Email>
	      <Homepage>http://www.cs.st-andrews.ac.uk/&tilde;alexk/</Homepage>
	      <Address>
            School of Computer Science<Br/>
            University of St Andrews<Br/>
            Jack Cole Building, North Haugh,<Br/>
            St Andrews, Fife, KY16 9SX, Scotland<Br/>
          </Address> 
  </Author>  

  <Author>Andrew Solomon
          <Email>andrew at illywhacker dot net</Email>
	      <Homepage>http://www.illywhacker.net/</Homepage>
	      <Address>
            Faculty of IT<Br/>
            University of Technology, Sydney<Br/>
            Broadway, NSW 2007<Br/>
            Australia<Br/>
          </Address> 
  </Author>
  
  <Date>30 March 2010</Date>

<Abstract>

<Index Key="SCSCP package">&OpenMath; package</Index> 

The &OpenMath; package provides an &OpenMath; phrasebook for &GAP;: 
it allows &GAP; users to import and export mathematical objects 
encoded in &OpenMath;, for the purpose of exchanging them with other 
&OpenMath;-enabled applications. 
</Abstract>

<Copyright>
The &OpenMath; package is free software; 
you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by 
the Free Software Foundation; either version 2 of the License, or 
(at your option) any later version. For details, see the FSF's own site
<URL>http://www.gnu.org/licenses/gpl.html</URL>.
<P/>

Additionally, the &OpenMath; package contains code developed at INRIA
(copyright INRIA), under the ESPRIT project number 24969 (&OpenMath;).
The user may not use the library in commercial products without seeking
permission from the &GAP; group (support@gap-system.org) and the 
CAFE team at INRIA SA (stephane.dalmas@sophia.inria.fr).

</Copyright>
  
<Acknowledgements>
On various stages the development of the &OpenMath; package was supported by:
<List>
  <Item>European Commission through ESPRIT grant EP 24969 
  <Q>Accessing and Using Mathematical Information Electronically</Q>
  (see <P/>
  <URL>http://web.archive.org/web/20040416013945/http://www.nag.co.uk/projects/OpenMath.html</URL>).</Item>
  <Item>EU FP6 Programme project 026133 
  <Q>SCIEnce - Symbolic Computation Infrastructure for Europe</Q>
  (see <URL>http://www.symbolic-computation.org/</URL>).</Item>
</List>  
We acknowledge with gratitude this support.<P/>
</Acknowledgements>

</TitlePage>

<TableOfContents/>

<Body>

<#Include SYSTEM "intro.xml">
<#Include SYSTEM "openmath.xml">
<#Include SYSTEM "extend.xml">

</Body>

<Bibliography Databases="manual"/>

<TheIndex/>

</Book>

=== gap-system/gap/pkg/recog/doc/recog.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd">

<!--

  recog.xml          recog package documentation                Max Neunhoeffer
                                                                and Ákos Seress

  Copyright (C) 2005, Lehrstuhl D für Mathematik, RWTH-Aachen

-->

<Book Name="recog">

<TitlePage>
    <Title>GAP 4 Package <Package>recog</Package></Title>
    <Subtitle>Group Recognition Methods</Subtitle>
    <Version>
      <#Include SYSTEM "../VERSION">
    </Version>
    <Author>Max Neunhöffer
<Address>
Lehrstuhl D für Mathematik,
RWTH Aachen,
Templergraben 64,
52062 Aachen,
Germany
</Address>
    <Email>max.neunhoeffer@math.rwth-aachen.de</Email>
    <Homepage>http://www.math.rwth-aachen.de/&tilde;Max.Neunhoeffer</Homepage>
    </Author>
    <Author>Ákos Seress
<Address>
Department of Mathematics,
The Ohio State University,
231 W 18th Avenue,
Columbus, OH 43210 USA 
</Address>
    <Email>akos@math.ohio-state.edu</Email>
    <Homepage>http://www.math.ohio-state.edu/people/display/display.php?ID=302
    </Homepage>
    </Author>
    <Date>Oktober 2005</Date>

<Copyright>
  &copyright; 2005 by Max Neunhöffer and Ákos Seress<P/>

  This package may be distributed under the terms and conditions of the
  GNU Public License Version 2 or higher.
</Copyright>

</TitlePage>

<!--  TableOfContents  . . . . . .  generate a table of contents   -->
<TableOfContents/>

<!--  The only chapter of the book  --> 
<Body>
<#Include SYSTEM "intro.xml">
<#Include SYSTEM "install.xml">
<#Include SYSTEM "methsel.xml">
<#Include SYSTEM "recognition.xml">
<#Include SYSTEM "afterrecog.xml">
<#Include SYSTEM "examples.xml">
<!-- more to come for the different recognition types -->
</Body>

<Bibliography Databases="recog"/>

<!--  And finally an index as well   -->
<TheIndex/>

</Book>

=== gap-system/gap/pkg/gapdoc/doc/gapdoc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd">

<!-- $Id: gapdoc.xml,v 1.15 2008/06/17 14:22:25 gap Exp $ -->

<!-- The documentation to the GAPDoc system. 
     Copyright 2000-2007 by Frank Lübeck and Max Neunhöffer
     Lehrstuhl D für Mathematik, RWTH Aachen, Germany -->
     
<Book Name="GAPDoc"> 

<TitlePage>
  <Title>&GAPDoc;</Title>
  <Version>( Version 
<#Include SYSTEM "../version">
 )
  </Version>
  <Author> Frank Lübeck 
    <Email>Frank.Luebeck@Math.RWTH-Aachen.De</Email>
    <Homepage>http://www.math.rwth-aachen.de/~Frank.Luebeck</Homepage>
  </Author>
  <Author> Max Neunhöffer 
    <Email>neunhoef at mcs.st-and.ac.uk</Email>
    <Homepage>http://www-groups.mcs.st-and.ac.uk/~neunhoef/</Homepage>
  </Author>
  <Date>June 2008</Date>
  <Copyright> &copyright; 2000-2008 by Frank Lübeck and Max Neunhöffer <P/>
              We adopt the copyright regulations of &GAP; as detailed in the 
              copyright notice in the &GAP; manual. </Copyright>
</TitlePage>

<TableOfContents/>

<Body>

<Ignore Remark="set SizeScreen for Example's">
<Example>
gap> SizeScreen([72,40]);;
</Example>
</Ignore>

<#Include SYSTEM "intro.xml">

<#Include SYSTEM "enter.xml">

<#Include SYSTEM "refdtd.xml">

<#Include SYSTEM "distr.xml">

<#Include SYSTEM "conv.xml">

<#Include SYSTEM "textutil.xml">

<#Include SYSTEM "bibutil.xml">


</Body>

<Appendix Label="app:3k+1"><Heading>The File <F>3k+1.xml</F></Heading>

Here is the complete source of the example &GAPDoc; document <F>3k+1.xml</F>
discussed in Section&nbsp;<Ref Sect="sec:3k+1expl" />.

<Listing Type="3k+1.xml">
<![CDATA[<#Include SYSTEM "../3k+1/3k+1.xml">]]></Listing>
</Appendix>

<Appendix Label="GAPDocdtd">
<Heading>The File <F>gapdoc.dtd</F></Heading>

For  easier reference  we  repeat  here the  complete  content  of the  file
<F>gapdoc.dtd</F>.

<Listing Type="gapdoc.dtd">
<![CDATA[<#Include SYSTEM "../gapdoc.dtd">
]]></Listing>

</Appendix>

<Appendix Label="bibxmlextdtd">
<Heading>The File <F>bibxmlext.dtd</F></Heading>

For  easier reference  we  repeat  here the  complete  content  of the  file
<F>bibxmlext.dtd</F> which is explained in <Ref Sect="BibXMLformat"/>.

<Listing Type="bibxmlext.dtd">
<![CDATA[<#Include SYSTEM "../bibxmlext.dtd">
]]></Listing>

</Appendix>
<Bibliography Databases="gapdocbib.xml" />

<TheIndex/>

</Book>

<!-- ==================================================================== -->
